name: Run Benchmark

on:
  workflow_dispatch:

env:
  DATASETS_PATH: ~/datasets
  OUTPUT_PATH: ./output
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: BluesoftInternship/Text-To-SQL-Benchmark
        token: ${{ secrets.PAT }}
        path: bench
        ref: dev

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        cd bench
        python -m pip install --upgrade pip
        pip install .

    - name: Cache Bird dataset
      id: cache-bird-dataset
      uses: actions/cache@v4
      env:
        cache-name: cache-bird-dataset
      with:
        path: ./dev
        key: bird-dataset

    - if: ${{ steps.cache-bird-dataset.outputs.cache-hit != 'true' }}
      name: Download Bird dataset
      run: |
        benchy download-dataset bird

    - name: Run benchmark
      run: |
        pwd
        benchy run bird -q ./dev/dev.json -d ./dev/dev_databases -l 20 -m gpt-4o
