name: Run Benchmark

on:
  workflow_dispatch:

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  QUESTIONS_LIMIT: ${{ vars.limit }}

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Set COMMIT_ID
      run: |
        if [[ -n "${{ github.sha }}" ]]; then 
          echo "COMMIT_ID=${{ github.sha }}" >> $GITHUB_ENV
        fi
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: BluesoftInternship/Text-To-SQL-Benchmark
        token: ${{ secrets.PAT }}
        path: benchmark
        ref: "feature/G1-103"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        cd benchmark
        python -m pip install --upgrade pip
        pip install .

    - if: ${{ vars.benchmark == 'bird' }}
      name: Cache Bird dataset
      id: cache-bird-dataset
      uses: actions/cache@v4
      env:
        cache-name: cache-bird-dataset
      with:
        path: ./bird
        key: bird-dataset

    - if: ${{ vars.benchmark == 'bird' && steps.cache-bird-dataset.outputs.cache-hit != 'true' }}
      name: Download Bird dataset
      run: |
        benchy download-dataset bird

    - if: ${{ vars.benchmark == 'spider' }}
      name: Cache Spider dataset
      id: cache-spider-dataset
      uses: actions/cache@v4
      env:
        cache-name: cache-spider-dataset
      with:
        path: ./spider
        key: bird-dataset

    - if: ${{ vars.benchmark == 'spider' && steps.cache-bird-dataset.outputs.cache-hit != 'true' }}
      name: Download Bird dataset
      run: |
        benchy download-dataset spider

    - name: Run benchmark
      run: |
        benchy run ${{ vars.benchmark }} -d ./${{ vars.benchmark }} -l $QUESTIONS_LIMIT -m gpt-3.5-turbo --save-json ./results

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: ./results/*.json
