name: Run Benchmark

on:
  workflow_dispatch:

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Set COMMIT_ID
      run: |
        if [[ -n "${{ github.sha }}" ]]; then 
          echo "COMMIT_ID=${{ github.sha }}" >> $GITHUB_ENV
        fi
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: BluesoftInternship/Text-To-SQL-Benchmark
        token: ${{ secrets.PAT }}
        path: benchmark
        ref: dev

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        cd benchmark
        python -m pip install --upgrade pip
        pip install .

    - name: Cache Bird dataset
      id: cache-bird-dataset
      uses: actions/cache@v4
      env:
        cache-name: cache-bird-dataset
      with:
        path: ./dev
        key: bird-dataset

    - if: ${{ steps.cache-bird-dataset.outputs.cache-hit != 'true' }}
      name: Download Bird dataset
      run: |
        benchy download-dataset bird -o ./datasets

    - name: Run benchmark
      run: |
        benchy run bird -d ./datasets/bird -l 20 -m gpt-4o

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: ./*.json
